# Generated by Django 3.2.4 on 2021-06-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_subject_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject_text',
        ),
    ]
