# Generated by Django 3.2.4 on 2021-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_subject_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_text', models.CharField(max_length=200)),
                ('isi_text', models.CharField(max_length=1000)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
