# Generated by Django 3.2.4 on 2021-06-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210627_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan_text', models.CharField(max_length=200)),
                ('pub_tgl', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pilihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan_text', models.CharField(max_length=200)),
                ('memilih', models.IntegerField(default=0)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pertanyaan')),
            ],
        ),
        migrations.DeleteModel(
            name='Isi',
        ),
    ]
