# Generated by Django 3.2.4 on 2021-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_pertanyaan_pub_tgl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=7)),
                ('nama', models.CharField(max_length=200)),
                ('jenis_kelamin', models.CharField(max_length=9)),
                ('tempat_lahir', models.CharField(max_length=200)),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('agama', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=500)),
                ('kota', models.CharField(max_length=200)),
            ],
        ),
    ]
