# Generated by Django 3.2.4 on 2021-06-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_anggota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_subject', models.CharField(max_length=1000)),
                ('blog_date', models.DateTimeField(verbose_name='blog published')),
            ],
        ),
        migrations.CreateModel(
            name='BlogChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_choice_text', models.CharField(max_length=200)),
                ('blog_votes', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.blog')),
            ],
        ),
    ]
