# Generated by Django 3.2.4 on 2021-06-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_blog_blogchoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anggota',
        ),
        migrations.RemoveField(
            model_name='pilihan',
            name='pertanyaan',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Pertanyaan',
        ),
        migrations.DeleteModel(
            name='Pilihan',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
