# Generated by Django 3.2.4 on 2021-06-27 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210628_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='blog_text',
        ),
        migrations.DeleteModel(
            name='BlogChoice',
        ),
        migrations.AddField(
            model_name='choice',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.blog'),
        ),
    ]
