# Generated by Django 3.2.4 on 2021-06-27 22:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210628_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_subject',
            field=tinymce.models.HTMLField(),
        ),
    ]
